[variables]
NODE_ENV = "production"
LOG_LEVEL = "info"
MCP_MONITOR_URL = "ws://localhost:2200"
USER_ID = "default-user"
SOURCE_NAME = "trae-mcp-monitor"
PORT = "3000"

[phases.install]
cmds = ["pnpm install --prod"]

[phases.build]
cmds = ["echo 'No build step required for MCP server'"]

[start]
cmd = "pnpm start"

# Build image configuration
buildImage = "node:18-alpine"